# $schema: https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      timezone: Europe/Belgrade # https://time.is/Serbia#time_difference
      time: '13:00'
    open-pull-requests-limit: 10
    reviewers:
      - emmitrovic
      - openinf/wg-a-team
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    labels:
      - 'dependencies'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      timezone: Europe/Belgrade # https://time.is/Serbia#time_difference
      time: '13:00'
    open-pull-requests-limit: 10
    reviewers:
      - emmitrovic
      - openinf/wg-a-team
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'build(deps-dev)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'deps-dev'
      - 'javascript'

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      timezone: Europe/Belgrade # https://time.is/Serbia#time_difference
      time: '13:00'
    open-pull-requests-limit: 10
    reviewers:
      - emmitrovic
      - openinf/wg-a-team
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'build(deps-dev)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'deps-dev'
      - 'ruby'

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
      day: tuesday
      timezone: Europe/Belgrade # https://time.is/Serbia#time_difference
      time: '13:00'
    open-pull-requests-limit: 10
    reviewers:
      - emmitrovic
      - openinf/wg-a-team
    commit-message:
      prefix: 'build(deps-dev)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'deps-dev'
      - 'docker'
