# $schema: https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      timezone: Europe/Belgrade # https://time.is/Serbia#time_difference
      time: '13:00'
    open-pull-requests-limit: 10
    reviewers:
      - emmitrovic
      - openinf/wg-a-team
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - 'dependencies'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      timezone: Europe/Belgrade # https://time.is/Serbia#time_difference
      time: '13:00'
    open-pull-requests-limit: 10
    reviewers:
      - emmitrovic
      - openinf/wg-a-team
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'build(deps-dev)'
    labels:
      - 'dependencies'
      - 'deps-dev'
      - 'javascript'
    ignore:
      # Ignore all major TypeScript type definition updates from DefinitelyTyped
      # for Node.js coming from Dependabot. We do not want any of those updates.
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      # Ignore monorepo dep bumping as they'll be better handled by Renovatebot
      # in the single-PRs that get made.
      - dependency-name: '@typescript-eslint/*'
      - dependency-name: '@babel/*'

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      timezone: Europe/Belgrade # https://time.is/Serbia#time_difference
      time: '13:00'
    open-pull-requests-limit: 10
    reviewers:
      - emmitrovic
      - openinf/wg-a-team
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'build(deps-dev)'
    labels:
      - 'dependencies'
      - 'deps-dev'
      - 'ruby'

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
      day: tuesday
      timezone: Europe/Belgrade # https://time.is/Serbia#time_difference
      time: '13:00'
    open-pull-requests-limit: 10
    reviewers:
      - emmitrovic
      - openinf/wg-a-team
    commit-message:
      prefix: 'build(deps-dev)'
    labels:
      - 'dependencies'
      - 'deps-dev'
      - 'docker'
