# Help community know how to financially support the maintenance and
# development of @openinf projects on GitHub using GitHub Sponsors.

github: [DerekNonGeneric, jorgebucaran, shellscape, smorimoto]
